image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm i && npm i -g @angular/cli
    command: npm run start

ports:
  - port: 4200

vscode:
  extensions:
    - Angular.ng-template@0.1100.2:N8OEQENlKzcVF6IHQQDnrg==